### ISSUE TITLE
ID 71: Provider only save certain kind of filter.

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#111]
LANE_CLOSED only available at TomTomt
CONSTRUCTION only available at Here.com

**Comment by Humus4theWin** [comment]
![image](https://user-images.githubusercontent.com/33117449/106326874-7cd99380-627d-11eb-9879-f98a1e5032ce.png)

CONSTRUCTION ist gar kein Incident Type und wird auf ROADWORKS gemapt
![image](https://user-images.githubusercontent.com/33117449/106326928-98dd3500-627d-11eb-9dc7-76c49719b780.png)

**Comment by vesela-stefanova** [comment]
Also ich weiß es nicht, vielleicht ist was wir im Frontend haben eine alte Liste von Types. Deswegen das Meeting am Sonntag - u.a. das zu klären
