### ISSUE TITLE
To many results in comparisonEvaluationOverTIme

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#120]
- http://18.184.210.66:8082/withDatabase/comparisonEvaluationOverTime?city=berlin gibt ergebnisse doppelt aus

> [{"tomTomIncidentsAmount":338,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 12:34"},{"tomTomIncidentsAmount":336,"hereIncidentsAmount":466,"sameIncidentAmount":0,"date":"2021-01-30 01:34"},{"tomTomIncidentsAmount":336,"hereIncidentsAmount":466,"sameIncidentAmount":0,"date":"2021-01-30 01:34"},{"tomTomIncidentsAmount":328,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 02:34"},{"tomTomIncidentsAmount":328,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 02:34"},{"tomTomIncidentsAmount":328,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 02:34"},{"tomTomIncidentsAmount":333,"hereIncidentsAmount":472,"sameIncidentAmount":0,"date":"2021-01-30 03:34"},{"tomTomIncidentsAmount":333,"hereIncidentsAmount":472,"sameIncidentAmount":0,"date":"2021-01-30 03:34"},{"tomTomIncidentsAmount":333,"hereIncidentsAmount":472,"sameIncidentAmount":0,"date":"2021-01-30 03:34"},{"tomTomIncidentsAmount":333,"hereIncidentsAmount":472,"sameIncidentAmount":0,"date":"2021-01-30 03:34"},{"tomTomIncidentsAmount":323,"hereIncidentsAmount":467,"sameIncidentAmount":0,"date":"2021-01-30 04:34"},{"tomTomIncidentsAmount":323,"hereIncidentsAmount":467,"sameIncidentAmount":0,"date":"2021-01-30 04:34"},{"tomTomIncidentsAmount":323,"hereIncidentsAmount":467,"sameIncidentAmount":0,"date":"2021-01-30 04:34"},{"tomTomIncidentsAmount":323,"hereIncidentsAmount":467,"sameIncidentAmount":0,"date":"2021-01-30 04:34"},{"tomTomIncidentsAmount":323,"hereIncidentsAmount":467,"sameIncidentAmount":0,"date":"2021-01-30 04:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":471,"sameIncidentAmount":0,"date":"2021-01-30 05:34"},{"tomTomIncidentsAmount":313,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":313,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":311,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 06:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":308,"hereIncidentsAmount":470,"sameIncidentAmount":0,"date":"2021-01-30 07:34"},{"tomTomIncidentsAmount":304,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":304,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":305,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 08:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":303,"hereIncidentsAmount":469,"sameIncidentAmount":0,"date":"2021-01-30 09:34"},{"tomTomIncidentsAmount":307,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 10:34"},{"tomTomIncidentsAmount":307,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 10:34"},{"tomTomIncidentsAmount":307,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 10:34"},{"tomTomIncidentsAmount":307,"hereIncidentsAmount":468,"sameIncidentAmount":0,"date":"2021-01-30 10:34"}]

Test is in `service/aggregator/AggregatorFromDatabaseBerlinWith3Requests`. Need to be completed

**Comment by basselfa** [comment]
all tests are completed and passes now in service/aggregator/AggregatorFromDatabaseBerlinWith3Requests

**Comment by qikangchen** [comment]
Maybe the bug was a side effect from issue #121.

**Comment by qikangchen** [comment]
This was indeed the problem
