### ISSUE TITLE
Ambiguous timestamp format in historization

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#130]
- currently the format for PM time like 20:00 will be 08:00. This leads to ambiguity

![image](https://user-images.githubusercontent.com/59102264/106439943-8aa73880-6478-11eb-843c-1feffa1cb3f3.png)

**Comment by vesela-stefanova** [comment]
1. it only applies for 00:00 shown as 12:00
2. the timestamp is read like this from the backend (see image below)

![image](https://user-images.githubusercontent.com/49861850/106446970-d35ef180-6478-11eb-9a7c-34a8993f9e8a.png)

**Comment by vesela-stefanova** [comment]
Data from the prod env is displayed via this code snippet and is not manipulated in the frontend:
```
.get(
            "http://18.196.171.7:8082/withDatabase/comparisonEvaluationOverTime/?city=" +
              this.city,
            {
              headers: { "Access-Control-Allow-Origin": "*" },
            }
          )
          .then((response) => {
            console.log(response.data);
```

**Comment by qikangchen** [comment]
**Tests:**
- `data/ComparisonEvaluationDTOTest#testMarshallingTime15_00()`: pass
- `data/ComparisonEvaluationDTOTest#testMarshallingTime00_20()`: pass
