### ISSUE TITLE
ID 56: Evaluation with Matcher

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#41]
**Implementation:**
`service/evaluation/Evaluation#calculateCandidates()`: 
- Split the Incidents from Request into TomTom And Here Incidents. Compare them with the two Matcher from sprint 8. 
- Thesis page 34

`service/evaluation/Evaluation#dropManifolds()`: 
- Drop manifolds. 
- Thesis page 42. 
- Confidence Level = EvaluationCandidate#getScore()
- Length Percent Difference from LengthMatcher#getLengthDifference()
- Points DIstance = SearchRadiusMatcher.getConfidence()

**Test:**
`service/evaluation/EvaluationTest`

**Comment by Humus4theWin** [comment]
Test Coverage
AngleMatcher | 100% (1/1) | 83% (5/6) | 94% (17/18)
-- | -- | -- | --
Evaluation | 100% (1/1) | 100% (10/10) | 100% (44/44)
Matcher | 100% (1/1) | 100% (1/1) | 100% (10/10)
SearchRadiusMatcher | 100% (1/1) | 100% (9/9) | 90% (27/30)

Tests
testCalculation() : pass
testdifferentIncidentLocal() : pass
testSameIncidentLocal() : pass
testManifolds() : pass

**Comment by qikangchen** [comment]
Es muss noch der score und die description von den candidates gesetzt werden.
