### ISSUE TITLE
ID 56: Matcher for Angle

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#42]
**Implementation:**
`service/evaluation/AngleMatcher`

**Test:**
`service/evaluation/AngleMatcherTest`

**Comment by Humus4theWin** [comment]
Tests:
testMatchingAngleUnder15Degree() - pass
testMisMatchAngleBetween22Point5And30Degree()  - pass
testMisMatchOver30Degree()  - pass
testMisMatch180Degree()  - pass

**Comment by qikangchen** [comment]
bitte noch codecoveage hinzuefuegen und ob du was an der dokumentation was hinzugefuegt hast.

Siehe beispiel https://github.com/basselfa/AMOS_Team1/issues/50
