### ISSUE TITLE
ID 56: Matcher for Search radius

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#43]
**Implementation:**
`service/evaluation/SearchRadiusMatcher`

**Test:**
`service/evaluation/SearchRadiusMatcher`

**Comment by Humus4theWin** [comment]
Code coverage

Matcher | 100% (1/1) | 100% (1/1) | 100% (10/10)
-- | -- | -- | --
SearchRadiusMatcher | 100% (1/1) | 100% (9/9) | 83% (25/30)



Tests
testReserveIncident() : pass
testIdenticalIncident() : pass
testOneMatchingPoint() : pass
testNoMatchingPoint() : pass
