### ISSUE TITLE
ID 56: Rest Endpoint Dummy: Get Comparison

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#47]
Dummy data for frontend.

**Implementation:**
`ResourceWithDummyData#getComparison()`

**Test:**
`ResourceWithDummyDataTest`

**Comment by qikangchen** [comment]
You need to write a Overview over Tests, Coverage and Documentation

**Comment by Arvazi** [comment]
Sending Dummy EvaluationCandidates with the same incidents

Tests:
ResourceWithDummyDataTest#testComparisonListAmount(): pass
ResourceWithDummyDataTest#testComparisonNotExisting(): pass

Codecoverage:
ResourceWithDummyData: 100%Class, 83%Method, 89%Line

Documentation:
no
