### ISSUE TITLE
ID 50: Rest Endpoint Dummy: Get Comparison evaluation over time  (Bar diagram)

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#48]
Dummy data for frontend

**Implementation:**
`ResourceWithDummyData#getComparisonEvaluationOverTime()`

**Test:**
`ResourceWithDummyDataTest`

**Comment by qikangchen** [comment]
Es fehlen noch Dokumentation ueber Test, Coverage und Dokumentationen. Siehe https://github.com/basselfa/AMOS_Team1/issues/50

**Comment by Arvazi** [comment]
Sending Dummy Comparison with 6 EvaluationCandidates with different Dates and Amounts of TomTomIncidents, HereIncidents and SameIncident 

Tests:
ResourceWithDummyDataTest#testComparisonEvaluationOverTime(): pass

Codecoverage:
ResourceWithDummyData: 100%Class, 16%Method, 58%Line

Documentation:
no
