### ISSUE TITLE
ID 47: MyRepo Implementation

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#81]

**Comment by Humus4theWin** [comment]
Tests are at database/DatabaseTest
#testStoreCityInforamtion()
#testDeleteCityInforamtion()

**Comment by basselfa** [comment]
Test:
 database/DatabaseTest

testStoreCityInforamtion(): pass
testDeleteCityInforamtion(): pass
Codcoverage:
Backend | 100% Class | 40% Method | 24% (63/85) Class
Documentation:
