### ISSUE TITLE
ID 47: Complete CityInformationResource

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#83]
https://spring.io/guides/tutorials/rest/

Post with JSON body Mapping

**Comment by qikangchen** [comment]
![image](https://user-images.githubusercontent.com/59102264/105627864-9a4fcd00-5e39-11eb-9479-1ac1c36dbeb9.png)

You need to create a new Data Transfer Object (DTO). Currently the Frontend need to express the `CityInformation` with an ID. But the frontend don't need to know the ID if they create a new `CityInformation`. 

So create for example `data/CityInformationIncomingDTO` like `data/CityInformation` without an ID. Change `@RequestBody CityInformation cityInformation` in `CityInformationResource` to `@RequestBody CityInformationIncomingDTO cityInformation `and map the data from `CityInformationIncomingDTO` to `CityInformation`.

Also complete Tests in `CityInformationResourceTest`. In `CityInformationResourceTest#testGetAllCityInformation` add CityInformation to the database before validating the returning objects. Do this also in the other tests. You need to bult the test like in `ResourceWithDummyDataTest`. Map the JSON to the objects.

**Comment by Arvazi** [comment]
CityInformationResourceTest
.testGetStatus200ForGetAllCityInformation() #pass
.testGetAllCityInformation() #pass
.testGetAllCityInformationWithUnMarshalling() #pass
.testDeleteCityInformation() #pass
.testAddCityInformation() #pass
