### ISSUE TITLE
ID 60: Add one more Matcher

### ISSUE THREAD

**Issue by qikangchen** [basselfa/AMOS_Team1#85]

**Comment by Arvazi** [comment]
Test Failed


DescriptionMatcherTest
26 msfailedtestEmptyStringNotMatch()
java.lang.AssertionError:
Expected: <0>
but: was <1>
Expected :
<0>
Actual :
<1>


________________________________

testDescrContained()
java.lang.AssertionError:
Expected: <1>
but: was <2>
Expected :
<1>
Actual :
<2>
